# Generated by Django 5.0.2 on 2024-02-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice1', to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice2', to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice3', to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice4', to='quiz.choice'),
        ),
    ]
